# Generated by Django 3.2.12 on 2025-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('customer_id', models.BigIntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financial_status', models.CharField(max_length=50)),
                ('fulfillment_status', models.CharField(max_length=50)),
                ('vendor_names', models.CharField(max_length=50)),
                ('payment_gateway', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('tracking_id', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('address', models.TextField()),
                ('parcel_status', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rcollection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latestdate', models.DateField()),
                ('seller_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gov_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rdcharge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.JSONField()),
                ('latestupdateofpercel', models.TextField()),
                ('shippment_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reverse_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('govaly_earning_per_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reverse_reason', models.TextField()),
                ('govaly_paid', models.BooleanField(default=False)),
                ('liveparcelstatus', models.TextField()),
            ],
        ),
    ]
