# Generated by Django 3.2.12 on 2025-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='financial_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fulfillment_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gov_earning',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='govaly_earning_per_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='govaly_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='latestupdateofpercel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='liveparcelstatus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='parcel_status',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_gateway',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='rcollection',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='rdcharge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='remarks',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='reverse_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='reverse_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='seller_earning',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='seller_payable',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shippment_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='vendor_names',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
