# Generated by Django 3.2.12 on 2025-05-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagment', '0002_auto_20250511_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='latestdate',
            field=models.DateField(null=True),
        ),
    ]
